# Generated by Django 3.0.8 on 2020-07-05 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uyeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Üye Adı', models.CharField(max_length=40)),
                ('Üye Kullanıcı Adı', models.CharField(max_length=16)),
                ('Üye Email', models.CharField(max_length=40)),
                ('Üye Ünvan', models.CharField(max_length=30)),
                ('Üye Şifre', models.TextField()),
                ('Üye Biyografi', models.CharField(max_length=200)),
                ('Üye Mesleği', models.CharField(max_length=20)),
                ('Üye Puanı', models.IntegerField(max_length=5)),
                ('Üye Saygınlığı', models.IntegerField(max_length=4)),
                ('Üye Avatarı', models.TextField()),
                ('Üye Rolü', models.IntegerField(max_length=1)),
                ('Üye Kayıt Tarihi', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
