# Generated by Django 3.0.8 on 2020-07-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AkademiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uyeler',
            name='Üye Rolü',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='uyeler',
            name='Üye Saygınlığı',
            field=models.IntegerField(),
        ),
    ]
