# Generated by Django 3.0.8 on 2020-07-05 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AkademiApp', '0003_auto_20200705_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumIslemleri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('İşlemi Yapan', models.CharField(max_length=16)),
                ('İşlem Tipi', models.IntegerField()),
                ('Üye Kayıt Tarihi', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ForumKonulari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Konu Başlığı', models.CharField(max_length=140)),
                ('Konu Detayı', models.TextField()),
                ('Konu Sahibi', models.CharField(max_length=16)),
                ('Konu Tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('Konu Kategorisi', models.CharField(max_length=20)),
                ('KonuOnay', models.BooleanField(default=False)),
            ],
        ),
    ]
